// Generated by https://quicktype.io


// comando para crear interfaz rapida: shift + command + v

export interface DashboardSummaryResponse {
    numberOfOrders:          number;
    paidOrders:              number;
    numberOfClients:         number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    lowInventory:            number;
    notPaidOrders:           number;
}
